# Generated by Django 3.1.7 on 2021-03-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('country_code', models.CharField(max_length=2, verbose_name='country code')),
                ('created', models.DateField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('assetClass', models.CharField(max_length=100)),
                ('counterParty', models.CharField(max_length=100)),
                ('dataSource', models.CharField(max_length=100)),
                ('instrumentId', models.CharField(max_length=100)),
                ('instrumentName', models.CharField(max_length=100)),
                ('orderId', models.CharField(max_length=100)),
                ('purchaseType', models.IntegerField(choices=[(1, 'BUY'), (2, 'SELL')])),
                ('orderSubmitted', models.DateTimeField()),
                ('tradeData', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('trader', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('color', models.CharField(max_length=30, verbose_name='color')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.IntegerField(choices=[(1, 'Sedan'), (2, 'Truck'), (3, 'SUV')], verbose_name='type')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManagement.manufacturer', verbose_name='manufacturer')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
